import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import WWW_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._tournament_info import resolve_tournament_season
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def player_stats_data(
    standings_df: pd.DataFrame,
    tournament_id: int,
    season_id: int,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches top player statistics for each team in the provided standings dataset.

    Teams that fail to fetch are logged as warnings and skipped rather than
    aborting the entire request.

    Args:
        standings_df: DataFrame generated by standings_data().
        tournament_id: The unique identifier for the tournament.
        season_id: The unique identifier for the season.
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.

    Returns:
        Player statistics with stat name/value pairs per player per team.

    Raises:
        InvalidParameterError: If an invalid data_source is given or standings_df is empty.
        DataNotAvailableError: If no player statistics are found.
    """
    validate_source(data_source)
    validate_df(standings_df, "standings_df")

    stats_list = []
    teams = standings_df[standings_df["category"] == "Total"]
    failed_teams: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in teams.iterrows():
            country = row["country"]
            tournament = row["tournament"]
            team_name = row["team_name"]
            team_id = row["team_id"]

            url = (
                f"{WWW_URLS[data_source]}/api/v1/team/{team_id}"
                f"/unique-tournament/{tournament_id}/season/{season_id}/top-players/overall"
            )
            try:
                data = client.get(url)
                for players in data.get("topPlayers", {}).values():
                    for player_data in players:
                        player = player_data.get("player", {})
                        player_id = player.get("id")
                        for stat, value in player_data.get("statistics", {}).items():
                            if stat in ("id", "type"):
                                continue
                            if isinstance(value, (dict, list)):
                                continue
                            stats_list.append({
                                "country": country,
                                "tournament": tournament,
                                "team_name": team_name,
                                "team_id": team_id,
                                "player_name": player.get("name"),
                                "player_id": player_id,
                                "position": player.get("position"),
                                "stat_name": stat,
                                "stat_value": value,
                            })
            except APIError as exc:
                logger.warning(
                    "Failed to fetch player stats for team_id=%s (%s): %s",
                    team_id, team_name, exc,
                )
                failed_teams.append(team_id)

    if failed_teams:
        logger.warning(
            "Could not retrieve player stats for %d team(s): %s", len(failed_teams), failed_teams
        )

    result_df = pd.DataFrame(stats_list).drop_duplicates(
        subset=["team_id", "player_id", "stat_name"]
    )
    if result_df.empty:
        raise DataNotAvailableError("No player statistics data found for the specified teams.")

    if enable_json_export or enable_excel_export:
        country, tournament_name, season_year = resolve_tournament_season(
            tournament_id, season_id, data_source=data_source, rate_limit=rate_limit
        )
        first = result_df.iloc[0]
        kwargs = dict(
            fn_name="player_stats_data",
            data_source=data_source,
            country=country or first["country"],
            tournament=tournament_name or first["tournament"],
            season=season_year,
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
