import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def player_national_team_data(
    squad_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches national team career statistics for each player in the provided squad dataset.

    Only 'overall' type entries are included (home/away splits are excluded).
    Players with no international career or failed fetches are logged and skipped.

    Args:
        squad_df: DataFrame generated by squad_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory where exported files are written. Defaults to '.'.

    Returns:
        One row per player per national team with columns: player_id, player_name,
        team_id, team_name, team_code, appearances, goals, debut_timestamp.

    Raises:
        InvalidParameterError: If an invalid data_source is given or squad_df is empty.
        DataNotAvailableError: If no national team data is found for any player.
    """
    validate_source(data_source)
    validate_df(squad_df, "squad_df")

    records = []
    unique_players = squad_df[["player_id", "player_name"]].drop_duplicates()
    failed_players: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, prow in unique_players.iterrows():
            player_id = prow["player_id"]
            player_name = prow["player_name"]
            url = f"{API_URLS[data_source]}/api/v1/player/{player_id}/national-team-statistics"
            try:
                data = client.get(url)
                for entry in data.get("statistics", []):
                    team = entry.get("team", {})
                    debut_ts = entry.get("debutTimestamp")
                    records.append({
                        "player_id": player_id,
                        "player_name": player_name,
                        "team_id": team.get("id"),
                        "team_name": team.get("name"),
                        "team_code": team.get("nameCode"),
                        "appearances": entry.get("appearances"),
                        "goals": entry.get("goals"),
                        "debut_timestamp": debut_ts,
                    })
            except APIError as exc:
                logger.warning(
                    "Failed to fetch national team stats for player_id=%s (%s): %s",
                    player_id, player_name, exc,
                )
                failed_players.append(player_id)

    if failed_players:
        logger.warning(
            "Could not retrieve national team stats for %d player(s): %s",
            len(failed_players), failed_players,
        )

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError(
            "No national team data found for the specified players."
        )

    if enable_json_export or enable_excel_export:
        first = squad_df.iloc[0]
        kwargs = dict(
            fn_name="player_national_team_data",
            data_source=data_source,
            country=first.get("country", "unknown"),
            tournament=first.get("tournament", "unknown"),
            season=None,
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
