import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def player_match_log_data(
    squad_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches match-by-match statistics for each player in the provided squad dataset,
    within a specific tournament and season.

    Args:
        squad_df: DataFrame generated by squad_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory where exported files are written. Defaults to '.'.

    Returns:
        DataFrame with per-match statistics per player: game_id, start_timestamp,
        home_team, away_team, score, status, and all available in-match stats
        (goals, assists, rating, minutes_played, etc.) as wide-format columns.

    Raises:
        InvalidParameterError: If an invalid data_source is given or squad_df is empty.
        DataNotAvailableError: If no match log data is found for any player.
    """
    validate_source(data_source)
    validate_df(squad_df, "squad_df")

    records = []
    unique_players = squad_df[["player_id", "player_name"]].drop_duplicates()
    failed_players: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, prow in unique_players.iterrows():
            player_id = prow["player_id"]
            player_name = prow["player_name"]
            page = 0
            while True:
                url = (
                    f"{API_URLS[data_source]}/api/v1/player/{player_id}"
                    f"/events/last/{page}"
                )
                try:
                    data = client.get(url)
                except APIError as exc:
                    logger.warning(
                        "Failed to fetch match log for player_id=%s (%s): %s",
                        player_id, player_name, exc,
                    )
                    failed_players.append(player_id)
                    break

                for ev in data.get("events", []):
                    stats = ev.get("playerStatistics") or {}
                    home_team = ev.get("homeTeam") or {}
                    away_team = ev.get("awayTeam") or {}
                    row = {
                        "player_id": player_id,
                        "player_name": player_name,
                        "game_id": ev.get("id"),
                        "start_timestamp": ev.get("startTimestamp"),
                        "tournament": (ev.get("tournament") or {}).get("name"),
                        "season": (ev.get("season") or {}).get("year"),
                        "home_team": home_team.get("name"),
                        "home_team_id": home_team.get("id"),
                        "away_team": away_team.get("name"),
                        "away_team_id": away_team.get("id"),
                        "home_score": (ev.get("homeScore") or {}).get("current"),
                        "away_score": (ev.get("awayScore") or {}).get("current"),
                        "status": (ev.get("status") or {}).get("description"),
                    }
                    for stat_name, stat_value in stats.items():
                        if not isinstance(stat_value, (dict, list)):
                            row[stat_name] = stat_value
                    records.append(row)

                if not data.get("hasNextPage", False):
                    break
                page += 1

    if failed_players:
        logger.warning(
            "Could not retrieve match log for %d player(s): %s",
            len(failed_players), failed_players,
        )

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError("No match log data found for the specified players.")

    if enable_json_export or enable_excel_export:
        first = squad_df.iloc[0]
        kwargs = dict(
            fn_name="player_match_log_data",
            data_source=data_source,
            country=first.get("country", ""),
            tournament=first.get("tournament", ""),
            season=result_df.iloc[0].get("season"),
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
