import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._tournament_info import resolve_tournament_season
from datafc.utils._helpers import _ts_to_age
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def player_data(
    squad_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches biographical and profile data for each player in the provided squad dataset.

    Returns one row per player with personal attributes not available in squad_data():
    date of birth, weight, jersey number, and current team snapshot at profile level.
    The player_id column from squad_data() is used as the lookup key.

    Args:
        squad_df: DataFrame generated by squad_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory where exported files are written. Defaults to '.'.

    Returns:
        DataFrame with columns: player_id, player_name, date_of_birth, age,
        nationality, nationality_id, height, weight, preferred_foot, jersey_number,
        position, market_value, market_currency, team_id, team_name.

    Raises:
        InvalidParameterError: If an invalid data_source is given or squad_df is empty.
        DataNotAvailableError: If no player data is found for any player.
    """
    validate_source(data_source)
    validate_df(squad_df, "squad_df")

    records = []
    unique_players = squad_df[["player_id", "player_name"]].drop_duplicates()
    failed_players: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, prow in unique_players.iterrows():
            player_id = prow["player_id"]
            player_name = prow["player_name"]
            url = f"{API_URLS[data_source]}/api/v1/player/{player_id}"
            try:
                data = client.get(url)
                p = data.get("player") or {}
                if not p:
                    logger.warning("Empty player response for player_id=%s", player_id)
                    failed_players.append(player_id)
                    continue
                country = p.get("country") or {}
                team = p.get("team") or {}
                dob_ts = p.get("dateOfBirthTimestamp")
                mv_raw = p.get("proposedMarketValueRaw") or {}
                records.append({
                    "player_id": player_id,
                    "player_name": p.get("name") or player_name,
                    "date_of_birth": (
                        datetime.fromtimestamp(dob_ts, tz=timezone.utc).strftime("%Y-%m-%d")
                        if dob_ts else None
                    ),
                    "age": p.get("age") if p.get("age") is not None else _ts_to_age(dob_ts),
                    "nationality": country.get("name"),
                    "nationality_id": country.get("id"),
                    "height": p.get("height"),
                    "weight": p.get("weight"),
                    "preferred_foot": p.get("preferredFoot"),
                    "jersey_number": p.get("jerseyNumber") or p.get("shirtNumber"),
                    "position": p.get("position"),
                    "market_value": mv_raw.get("value"),
                    "market_currency": mv_raw.get("currency"),
                    "team_id": team.get("id"),
                    "team_name": team.get("name"),
                })
            except APIError as exc:
                logger.warning(
                    "Failed to fetch profile for player_id=%s (%s): %s",
                    player_id, player_name, exc,
                )
                failed_players.append(player_id)

    if failed_players:
        logger.warning(
            "Could not retrieve profile for %d player(s): %s",
            len(failed_players), failed_players,
        )

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError("No player profile data found for the specified players.")

    if enable_json_export or enable_excel_export:
        first = squad_df.iloc[0]
        t_id = int(first.get("tournament_id") or 0)
        s_id = int(first.get("season_id") or 0)
        _, _, season_year = resolve_tournament_season(
            t_id, s_id, data_source=data_source, rate_limit=rate_limit
        ) if t_id and s_id else ("", "", None)
        kwargs = dict(
            fn_name="player_data",
            data_source=data_source,
            country=first.get("country", "unknown"),
            tournament=first.get("tournament", "unknown"),
            season=season_year,
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
