import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._tournament_info import resolve_tournament_season
from datafc.utils._helpers import _cast_int_cols
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)

_TRANSFER_TYPES = {1: "loan", 2: "permanent", 3: "free", 4: "end_of_contract"}


def player_transfers_data(
    squad_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches full transfer history for each player in the provided squad dataset.

    Players that fail to fetch are logged as warnings and skipped.

    Args:
        squad_df: DataFrame generated by squad_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory where exported files are written. Defaults to '.'.

    Returns:
        Transfer history with columns: player_id, player_name, transfer_date,
        from_team_id, from_team_name, to_team_id, to_team_name, transfer_type,
        fee, fee_currency.

    Raises:
        InvalidParameterError: If an invalid data_source is given or squad_df is empty.
        DataNotAvailableError: If no transfer data is found for any player.
    """
    validate_source(data_source)
    validate_df(squad_df, "squad_df")

    records = []
    unique_players = squad_df[["player_id", "player_name"]].drop_duplicates()
    failed_players: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in unique_players.iterrows():
            player_id = row["player_id"]
            player_name = row["player_name"]
            url = f"{API_URLS[data_source]}/api/v1/player/{player_id}/transfer-history"
            try:
                data = client.get(url)
                for transfer in data.get("transferHistory", []):
                    date_ts = transfer.get("transferDate")
                    fee_raw = transfer.get("transferFee")
                    records.append({
                        "player_id": player_id,
                        "player_name": player_name,
                        "transfer_date": (
                            datetime.fromtimestamp(date_ts, tz=timezone.utc).strftime("%Y-%m-%d")
                            if date_ts else None
                        ),
                        "from_team_id": (transfer.get("transferFrom") or {}).get("id"),
                        "from_team_name": (transfer.get("transferFrom") or {}).get("name"),
                        "to_team_id": (transfer.get("transferTo") or {}).get("id"),
                        "to_team_name": (transfer.get("transferTo") or {}).get("name"),
                        "transfer_type": _TRANSFER_TYPES.get(transfer.get("type"), "unknown"),
                        "fee": fee_raw.get("value") if isinstance(fee_raw, dict) else None,
                        "fee_currency": fee_raw.get("currency") if isinstance(fee_raw, dict) else None,
                    })
            except APIError as exc:
                logger.warning(
                    "Failed to fetch transfers for player_id=%s (%s): %s",
                    player_id, player_name, exc,
                )
                failed_players.append(player_id)

    if failed_players:
        logger.warning(
            "Could not retrieve transfers for %d player(s): %s",
            len(failed_players), failed_players,
        )

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError("No transfer data found for the specified players.")
    _cast_int_cols(result_df, "from_team_id", "to_team_id")

    if enable_json_export or enable_excel_export:
        first = squad_df.iloc[0]
        t_id = int(first.get("tournament_id") or 0)
        s_id = int(first.get("season_id") or 0)
        _, _, season_year = resolve_tournament_season(
            t_id, s_id, data_source=data_source, rate_limit=rate_limit
        ) if t_id and s_id else ("", "", None)
        kwargs = dict(
            fn_name="player_transfers_data",
            data_source=data_source,
            country=first.get("country", "unknown"),
            tournament=first.get("tournament", "unknown"),
            season=season_year,
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
