import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def pregame_form_data(
    match_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches pre-game form data for each match in the provided match dataset.

    Returns the last 5 results, average rating, league position, and squad market
    value for both the home and away team before each match.

    Args:
        match_df: DataFrame generated by match_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory where exported files are written. Defaults to '.'.

    Returns:
        DataFrame with columns: country, tournament, season, week, game_id,
        team (home/away), avg_rating, position, value, form_1..form_5
        (most recent result last).

    Raises:
        InvalidParameterError: If an invalid data_source is given or match_df is empty.
        DataNotAvailableError: If no pre-game form data is found.
    """
    validate_source(data_source)
    validate_df(match_df, "match_df")

    records = []
    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in match_df.iterrows():
            country, tournament, season, week, game_id = row[
                ["country", "tournament", "season", "week", "game_id"]
            ]
            try:
                data = client.get(f"{API_URLS[data_source]}/api/v1/event/{game_id}/pregame-form")
            except APIError as exc:
                logger.warning(
                    "Failed to fetch pregame form for game_id=%s: %s", game_id, exc
                )
                continue

            for side in ("homeTeam", "awayTeam"):
                team_form = data.get(side)
                if not isinstance(team_form, dict):
                    continue
                form_results = team_form.get("form", [])
                form_row = {
                    "country": country,
                    "tournament": tournament,
                    "season": season,
                    "week": week,
                    "game_id": game_id,
                    "team": "home" if side == "homeTeam" else "away",
                    "avg_rating": team_form.get("avgRating"),
                    "position": team_form.get("position"),
                    "value": team_form.get("value"),
                }
                for i, result in enumerate(form_results, start=1):
                    form_row[f"form_{i}"] = result
                records.append(form_row)

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError("No pre-game form data found for the specified matches.")

    for col in ("avg_rating", "value", "position"):
        if col in result_df.columns:
            result_df[col] = pd.to_numeric(result_df[col], errors="coerce")

    if enable_json_export or enable_excel_export:
        first = result_df.iloc[0]
        kwargs = dict(
            fn_name="pregame_form_data",
            data_source=data_source,
            country=first["country"],
            tournament=first["tournament"],
            season=first["season"],
            week_number=first["week"],
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
