import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._tournament_info import resolve_tournament_season
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def team_data(
    standings_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches profile and infrastructure data for each team in the provided standings dataset.

    Returns one row per team with information not available in standings_data() or squad_data():
    founding year, stadium name and capacity, kit colours, and current manager details.

    Args:
        standings_df: DataFrame generated by standings_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory where exported files are written. Defaults to '.'.

    Returns:
        DataFrame with columns: country, tournament, team_id, team_name, short_name,
        slug, national, country_name, country_id, primary_color, secondary_color,
        text_color, venue_id, venue_name, venue_capacity, venue_city,
        manager_id, manager_name, manager_country.

    Raises:
        InvalidParameterError: If an invalid data_source is given or standings_df is empty.
        DataNotAvailableError: If no team data is found for any team.
    """
    validate_source(data_source)
    validate_df(standings_df, "standings_df")

    records = []
    teams = standings_df[standings_df["category"] == "Total"]
    failed_teams: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in teams.iterrows():
            team_id = row["team_id"]
            team_name = row["team_name"]
            url = f"{API_URLS[data_source]}/api/v1/team/{team_id}"
            try:
                data = client.get(url)
                t = data.get("team") or {}
                if not t:
                    logger.warning("Empty team response for team_id=%s", team_id)
                    failed_teams.append(team_id)
                    continue
                country = t.get("country") or {}
                venue = t.get("venue") or {}
                stadium = venue.get("stadium") or {}
                manager = t.get("manager") or {}
                colors = t.get("teamColors") or {}
                records.append({
                    "country": row["country"],
                    "tournament": row["tournament"],
                    "team_id": team_id,
                    "team_name": t.get("name") or team_name,
                    "short_name": t.get("shortName") or t.get("nameCode"),
                    "slug": t.get("slug"),
                    "national": t.get("national"),
                    "country_name": country.get("name"),
                    "country_id": country.get("id"),
                    "primary_color": colors.get("primary"),
                    "secondary_color": colors.get("secondary"),
                    "text_color": colors.get("text"),
                    "venue_id": venue.get("id"),
                    "venue_name": stadium.get("name") or venue.get("name"),
                    "venue_capacity": stadium.get("capacity"),
                    "venue_city": (venue.get("city") or {}).get("name"),
                    "manager_id": manager.get("id"),
                    "manager_name": manager.get("name"),
                    "manager_country": (manager.get("country") or {}).get("name"),
                })
            except APIError as exc:
                logger.warning(
                    "Failed to fetch profile for team_id=%s (%s): %s",
                    team_id, team_name, exc,
                )
                failed_teams.append(team_id)

    if failed_teams:
        logger.warning(
            "Could not retrieve profile for %d team(s): %s",
            len(failed_teams), failed_teams,
        )

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError("No team profile data found for the specified teams.")

    if enable_json_export or enable_excel_export:
        first = standings_df.iloc[0]
        t_id = int(first.get("tournament_id") or 0)
        s_id = int(first.get("season_id") or 0)
        _, _, season_year = resolve_tournament_season(
            t_id, s_id, data_source=data_source, rate_limit=rate_limit
        ) if t_id and s_id else ("", "", None)
        kwargs = dict(
            fn_name="team_data",
            data_source=data_source,
            country=first.get("country", "unknown"),
            tournament=first.get("tournament", "unknown"),
            season=season_year,
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
