import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._helpers import _cast_int_cols
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)

_TRANSFER_TYPES = {1: "loan", 2: "permanent", 3: "free", 4: "end_of_contract"}


def team_transfers_data(
    standings_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches transfer history for each team in the provided standings dataset.

    Both incoming (in) and outgoing (out) transfers are returned.
    Teams that fail to fetch are logged as warnings and skipped.

    Args:
        standings_df: DataFrame generated by standings_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory where exported files are written. Defaults to '.'.

    Returns:
        Transfer records with columns: country, tournament, team_name, team_id,
        direction, player_id, player_name, transfer_date, from_team_id,
        from_team_name, to_team_id, to_team_name, transfer_type, fee, fee_currency.

    Raises:
        InvalidParameterError: If an invalid data_source is given or standings_df is empty.
        DataNotAvailableError: If no transfer data is found for any team.
    """
    validate_source(data_source)
    validate_df(standings_df, "standings_df")

    records = []
    teams = standings_df[standings_df["category"] == "Total"]
    failed_teams: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in teams.iterrows():
            country = row["country"]
            tournament = row["tournament"]
            team_name = row["team_name"]
            team_id = row["team_id"]

            url = f"{API_URLS[data_source]}/api/v1/team/{team_id}/transfers"
            try:
                data = client.get(url)
                for direction in ("transfersIn", "transfersOut"):
                    dir_label = "in" if direction == "transfersIn" else "out"
                    for transfer in data.get(direction, []):
                        player = transfer.get("player", {})
                        date_ts = transfer.get("transferDate")
                        fee_raw = transfer.get("transferFee")
                        records.append({
                            "country": country,
                            "tournament": tournament,
                            "team_name": team_name,
                            "team_id": team_id,
                            "direction": dir_label,
                            "player_id": player.get("id"),
                            "player_name": player.get("name"),
                            "transfer_date": (
                                datetime.fromtimestamp(date_ts, tz=timezone.utc).strftime("%Y-%m-%d")
                                if date_ts else None
                            ),
                            "from_team_id": (transfer.get("transferFrom") or {}).get("id"),
                            "from_team_name": (transfer.get("transferFrom") or {}).get("name"),
                            "to_team_id": (transfer.get("transferTo") or {}).get("id"),
                            "to_team_name": (transfer.get("transferTo") or {}).get("name"),
                            "transfer_type": _TRANSFER_TYPES.get(transfer.get("type"), "unknown"),
                            "fee": fee_raw.get("value") if isinstance(fee_raw, dict) else None,
                            "fee_currency": fee_raw.get("currency") if isinstance(fee_raw, dict) else None,
                        })
            except APIError as exc:
                logger.warning(
                    "Failed to fetch transfers for team_id=%s (%s): %s",
                    team_id, team_name, exc,
                )
                failed_teams.append(team_id)

    if failed_teams:
        logger.warning(
            "Could not retrieve transfers for %d team(s): %s",
            len(failed_teams), failed_teams,
        )

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError("No transfer data found for the specified teams.")
    _cast_int_cols(result_df, "from_team_id", "to_team_id")

    if enable_json_export or enable_excel_export:
        first = result_df.iloc[0]
        kwargs = dict(
            fn_name="team_transfers_data",
            data_source=data_source,
            country=first["country"],
            tournament=first["tournament"],
            season=None,
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
