import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._helpers import _cast_int_cols
from datafc.sofascore._parsers import parse_match_details_records
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def match_details_data(
    match_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches referee and venue details for each match.

    Returns one row per match. Referee columns (``referee_id``, ``referee_name``,
    ``referee_country``, ``referee_yellow_cards``, ``referee_red_cards``,
    ``referee_games``) and venue columns (``venue_id``, ``venue_name``,
    ``venue_city``, ``venue_country``, ``venue_capacity``) are ``None`` when
    not available for a match.

    Args:
        match_df: DataFrame generated by match_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory for exported files. Defaults to current directory.

    Returns:
        Match details with referee and venue info per match.

    Raises:
        InvalidParameterError: If an invalid data_source is given or match_df is empty.
        DataNotAvailableError: If no detail data is returned.
        APIError: On HTTP errors from the Sofascore API.
    """
    validate_source(data_source)
    validate_df(match_df, "match_df")

    records = []
    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in match_df.iterrows():
            country, tournament, season, week, game_id = row[
                ["country", "tournament", "season", "week", "game_id"]
            ]
            try:
                data = client.get(f"{API_URLS[data_source]}/api/v1/event/{game_id}")
                record = parse_match_details_records(
                    data, country, tournament, season, week, game_id
                )
                if record:
                    records.append(record)
            except APIError as exc:
                logger.warning("Failed to fetch details for game_id=%s: %s", game_id, exc)

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError("No match detail data found for the specified parameters.")
    _cast_int_cols(result_df, "referee_id")

    if enable_json_export or enable_excel_export:
        first = result_df.iloc[0]
        kwargs = dict(
            fn_name="match_details_data",
            data_source=data_source,
            country=first["country"],
            tournament=first["tournament"],
            season=first["season"],
            week_number=first["week"],
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
