import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._helpers import _safe_apply
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def goal_networks_data(
    match_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches goal network (passing network) data for each match.

    Args:
        match_df: DataFrame generated by match_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.

    Returns:
        Goal network actions with player coordinates and pass end points.

    Raises:
        InvalidParameterError: If an invalid data_source is given or match_df is empty.
        DataNotAvailableError: If no passing network data is found.
        APIError: On HTTP errors from the Sofascore API.
    """
    validate_source(data_source)
    validate_df(match_df, "match_df")

    def _coord(coords, key):
        return coords.get(key) if isinstance(coords, dict) else None

    incidents_frames = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in match_df.iterrows():
            country, tournament, season, week, game_id = row[
                ["country", "tournament", "season", "week", "game_id"]
            ]
            try:
                data = client.get(f"{API_URLS[data_source]}/api/v1/event/{game_id}/incidents")
            except APIError as exc:
                logger.warning("Failed to fetch goal networks for game_id=%s: %s", game_id, exc)
                continue

            incidents = data.get("incidents", [])
            if isinstance(incidents, list) and incidents:
                frame = pd.DataFrame(incidents)
                frame["country"] = country
                frame["tournament"] = tournament
                frame["season"] = season
                frame["week"] = week
                frame["game_id"] = game_id
                incidents_frames.append(frame)

    if not incidents_frames:
        raise DataNotAvailableError("No goal network data found for the specified parameters.")

    incidents_df = pd.concat(incidents_frames, ignore_index=True)

    if "footballPassingNetworkAction" not in incidents_df.columns:
        raise DataNotAvailableError("No passing network actions found in incident data.")

    actions_list = []
    for _, row in incidents_df[
        ["id", "footballPassingNetworkAction", "country", "tournament", "season", "week", "game_id"]
    ].iterrows():
        if not isinstance(row["footballPassingNetworkAction"], list):
            continue
        for event in row["footballPassingNetworkAction"]:
            event = dict(event)
            event["id"] = row["id"]
            event.update({
                "country": row["country"],
                "tournament": row["tournament"],
                "season": row["season"],
                "week": row["week"],
                "game_id": row["game_id"],
            })
            actions_list.append(event)

    if not actions_list:
        raise DataNotAvailableError("No passing network actions found.")

    raw_df = pd.DataFrame(actions_list)

    result_df = raw_df.assign(
        player_name=raw_df["player"].apply(lambda p: p.get("name") if isinstance(p, dict) else None),
        player_id=raw_df["player"].apply(lambda p: p.get("id") if isinstance(p, dict) else None),
        event_type=raw_df["eventType"],
        player_x=raw_df["playerCoordinates"].apply(lambda c: _coord(c, "x")),
        player_y=raw_df["playerCoordinates"].apply(lambda c: _coord(c, "y")),
        pass_end_x=_safe_apply(raw_df, "passEndCoordinates", lambda c: _coord(c, "x")),
        pass_end_y=_safe_apply(raw_df, "passEndCoordinates", lambda c: _coord(c, "y")),
        is_assist=_safe_apply(raw_df, "isAssist"),
        goalkeeper_x=_safe_apply(raw_df, "gkCoordinates", lambda c: _coord(c, "x")),
        goalkeeper_y=_safe_apply(raw_df, "gkCoordinates", lambda c: _coord(c, "y")),
        goal_shot_x=_safe_apply(raw_df, "goalShotCoordinates", lambda c: _coord(c, "x")),
        goal_shot_y=_safe_apply(raw_df, "goalShotCoordinates", lambda c: _coord(c, "y")),
        goal_mouth_x=_safe_apply(raw_df, "goalMouthCoordinates", lambda c: _coord(c, "x")),
        goal_mouth_y=_safe_apply(raw_df, "goalMouthCoordinates", lambda c: _coord(c, "y")),
        goalkeeper_name=_safe_apply(raw_df, "goalkeeper", lambda gk: gk.get("name") if isinstance(gk, dict) else None),
        goalkeeper_id=_safe_apply(raw_df, "goalkeeper", lambda gk: gk.get("id") if isinstance(gk, dict) else None),
    )[[
        "country", "tournament", "season", "week", "game_id",
        "player_name", "player_id", "event_type",
        "player_x", "player_y", "pass_end_x", "pass_end_y",
        "is_assist", "id",
        "goalkeeper_x", "goalkeeper_y",
        "goal_shot_x", "goal_shot_y",
        "goal_mouth_x", "goal_mouth_y",
        "goalkeeper_name", "goalkeeper_id",
    ]]

    if enable_json_export or enable_excel_export:
        first = result_df.iloc[0]
        kwargs = dict(
            fn_name="goal_networks_data",
            data_source=data_source,
            country=first["country"],
            tournament=first["tournament"],
            season=first["season"],
            week_number=first["week"],
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
