import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._helpers import _cast_int_cols
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def player_career_stats_data(
    squad_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches career statistics (all seasons) for each player in the provided squad dataset.

    Only 'overall' type entries are included (home/away splits are excluded).
    Players that fail to fetch are logged as warnings and skipped.

    Args:
        squad_df: DataFrame generated by squad_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.
        output_dir: Directory where exported files are written. Defaults to '.'.

    Returns:
        Career statistics per player per season/tournament in long format
        (one row per player-season-stat combination).

    Raises:
        InvalidParameterError: If an invalid data_source is given or squad_df is empty.
        DataNotAvailableError: If no career stats are found for any player.
    """
    validate_source(data_source)
    validate_df(squad_df, "squad_df")

    records = []
    unique_players = squad_df[["player_id", "player_name"]].drop_duplicates()
    failed_players: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in unique_players.iterrows():
            player_id = row["player_id"]
            player_name = row["player_name"]
            try:
                seasons_data = client.get(
                    f"{API_URLS[data_source]}/api/v1/player/{player_id}/statistics/seasons"
                )
                for entry in seasons_data.get("uniqueTournamentSeasons", []):
                    tournament = entry.get("uniqueTournament", {})
                    tid = tournament.get("id")
                    for season in entry.get("seasons", []):
                        sid = season.get("id")
                        try:
                            stats_data = client.get(
                                f"{API_URLS[data_source]}/api/v1/player/{player_id}"
                                f"/unique-tournament/{tid}/season/{sid}/statistics/overall"
                            )
                        except APIError:
                            continue
                        team = stats_data.get("team", {})
                        for stat_name, stat_value in stats_data.get("statistics", {}).items():
                            if isinstance(stat_value, (dict, list)):
                                continue
                            records.append({
                                "player_id": player_id,
                                "player_name": player_name,
                                "tournament_id": tid,
                                "tournament_name": tournament.get("name"),
                                "season_id": sid,
                                "season_name": season.get("year"),
                                "team_id": team.get("id"),
                                "team_name": team.get("name"),
                                "stat": stat_name,
                                "value": stat_value,
                            })
            except APIError as exc:
                logger.warning(
                    "Failed to fetch career stats for player_id=%s (%s): %s",
                    player_id, player_name, exc,
                )
                failed_players.append(player_id)

    if failed_players:
        logger.warning(
            "Could not retrieve career stats for %d player(s): %s",
            len(failed_players), failed_players,
        )

    result_df = pd.DataFrame(records)
    if result_df.empty:
        raise DataNotAvailableError("No career stats data found for the specified players.")
    _cast_int_cols(result_df, "team_id")

    if enable_json_export or enable_excel_export:
        first = squad_df.iloc[0]
        kwargs = dict(
            fn_name="player_career_stats_data",
            data_source=data_source,
            country=first.get("country", "unknown"),
            tournament=first.get("tournament", "unknown"),
            season=None,
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
