from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.exceptions import APIError, DataNotAvailableError, InvalidParameterError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache


def coordinates_data(
    lineups_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches heatmap coordinate data for each player in the provided lineup dataset.

    Players with no heatmap data (e.g. short substitute appearances) are silently skipped.

    Args:
        lineups_df: DataFrame generated by lineups_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.

    Returns:
        Heatmap x/y coordinates per player per match.

    Raises:
        InvalidParameterError: If an invalid data_source is given or lineups_df is empty.
        DataNotAvailableError: If no heatmap data is found for any player.
        APIError: On non-404 HTTP errors from the Sofascore API.
    """
    validate_source(data_source)
    validate_df(lineups_df, "lineups_df")

    unique_players = lineups_df[[
        "country", "tournament", "season", "week", "game_id", "team", "player_id", "player_name"
    ]].drop_duplicates()

    if unique_players.empty:
        raise InvalidParameterError("No unique players found in lineups_df.")

    heatmap_data = []
    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in unique_players.iterrows():
            url = (
                f"{API_URLS[data_source]}/api/v1/event/{row['game_id']}"
                f"/player/{row['player_id']}/heatmap"
            )
            try:
                data = client.get(url)
            except APIError as exc:
                if exc.status_code in (404, 403):
                    continue
                raise

            for point in data.get("heatmap", []):
                if not isinstance(point, dict) or "x" not in point or "y" not in point:
                    continue
                heatmap_data.append({
                    "country": row["country"],
                    "tournament": row["tournament"],
                    "season": row["season"],
                    "week": row["week"],
                    "game_id": row["game_id"],
                    "team": row["team"],
                    "player_id": row["player_id"],
                    "player_name": row["player_name"],
                    "x": point["x"],
                    "y": point["y"],
                })

    result_df = pd.DataFrame(heatmap_data)
    if result_df.empty:
        raise DataNotAvailableError("No heatmap data found for the specified players.")

    if enable_json_export or enable_excel_export:
        first = lineups_df.iloc[0]
        kwargs = dict(
            fn_name="coordinates_data",
            data_source=data_source,
            country=first["country"],
            tournament=first["tournament"],
            season=first["season"],
            week_number=first["week"],
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
