import logging
from typing import TYPE_CHECKING, Optional
import pandas as pd
from datafc.utils._client import SofascoreClient
from datafc.utils._save_files import save_json, save_excel
from datafc.utils._config import API_URLS
from datafc.utils._validate import validate_source, validate_df
from datafc.utils._tournament_info import resolve_tournament_season
from datafc.utils._helpers import _ts_to_age
from datafc.exceptions import APIError, DataNotAvailableError

if TYPE_CHECKING:
    from datafc.utils._cache import DiskCache

logger = logging.getLogger(__name__)


def squad_data(
    standings_df: pd.DataFrame,
    data_source: str = "sofascore",
    rate_limit: float = 2.0,
    cache: Optional["DiskCache"] = None,
    enable_json_export: bool = False,
    enable_excel_export: bool = False,
    output_dir: str = ".",
) -> pd.DataFrame:
    """
    Fetches squad roster data for each team in the provided standings dataset.

    Teams that fail to fetch are logged as warnings and skipped rather than
    aborting the entire request.

    Args:
        standings_df: DataFrame generated by standings_data().
        data_source: The data source ('sofavpn' or 'sofascore'). Defaults to 'sofascore'.
        rate_limit: Maximum requests per second. Defaults to 2.0.
        cache: Optional DiskCache instance. Cached responses skip the API call.
        enable_json_export: If True, saves output as JSON. Defaults to False.
        enable_excel_export: If True, saves output as Excel. Defaults to False.

    Returns:
        Squad data with player details including age, height, contract, and market value.

    Raises:
        InvalidParameterError: If an invalid data_source is given or standings_df is empty.
        DataNotAvailableError: If no squad data is found for any team.
    """
    validate_source(data_source)
    validate_df(standings_df, "standings_df")

    squad_list = []
    teams = standings_df[standings_df["category"] == "Total"]
    failed_teams: list = []

    with SofascoreClient(rate_limit=rate_limit, cache=cache) as client:
        for _, row in teams.iterrows():
            country = row["country"]
            tournament = row["tournament"]
            team_name = row["team_name"]
            team_id = row["team_id"]

            tournament_id = row.get("tournament_id", 0)
            season_id = row.get("season_id", 0)
            url = f"{API_URLS[data_source]}/api/v1/team/{team_id}/players"
            try:
                data = client.get(url)
                for player_info in data.get("players", []):
                    player = player_info.get("player")
                    if not player:
                        continue
                    squad_list.append({
                        "country": country,
                        "tournament": tournament,
                        "tournament_id": tournament_id,
                        "season_id": season_id,
                        "team_name": team_name,
                        "team_id": team_id,
                        "player_name": player.get("name"),
                        "player_id": player.get("id"),
                        "age": _ts_to_age(player.get("dateOfBirthTimestamp")),
                        "height": player.get("height"),
                        "player_country": player.get("country", {}).get("name"),
                        "position": player.get("position"),
                        "preferred_foot": player.get("preferredFoot"),
                        "contract_until": player.get("contractUntilTimestamp"),
                        "market_value": player.get("proposedMarketValueRaw", {}).get("value"),
                        "market_currency": player.get("proposedMarketValueRaw", {}).get("currency"),
                    })
            except APIError as exc:
                logger.warning(
                    "Failed to fetch squad data for team_id=%s (%s): %s",
                    team_id, team_name, exc,
                )
                failed_teams.append(team_id)

    if failed_teams:
        logger.warning(
            "Could not retrieve squad for %d team(s): %s", len(failed_teams), failed_teams
        )

    result_df = pd.DataFrame(squad_list)
    if result_df.empty:
        raise DataNotAvailableError("No squad data found for the specified teams.")

    if enable_json_export or enable_excel_export:
        first = result_df.iloc[0]
        t_id = int(first.get("tournament_id") or 0)
        s_id = int(first.get("season_id") or 0)
        _, _, season_year = resolve_tournament_season(
            t_id, s_id, data_source=data_source, rate_limit=rate_limit
        ) if t_id and s_id else ("", "", None)
        kwargs = dict(
            fn_name="squad_data",
            data_source=data_source,
            country=first["country"],
            tournament=first["tournament"],
            season=season_year,
        )
        if enable_json_export:
            save_json(data=result_df, **kwargs, output_dir=output_dir)
        if enable_excel_export:
            save_excel(data=result_df, **kwargs, output_dir=output_dir)

    return result_df
